version: '3'
services:
  db:
    image: postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
    - postgresql_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  postgresql_data:
  bundle_data:
  node_modules: